Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -3,6 +3,9 @@
 
 name: Go
 
+env:
+  GIN_MODE: release
+
 on:
   push:
     branches: [ "main" ]
@@ -13,16 +16,32 @@ jobs:
 
   build:
     runs-on: ubuntu-latest
+
+    permissions:
+      checks: write
+      
     steps:
     - uses: actions/checkout@v4
 
     - name: Set up Go
       uses: actions/setup-go@v4
       with:
-        go-version: '1.20'
+        go-version: '1.22'
+        cache: true
 
     - name: Build
-      run: go build -v ./...
+      run: |
+        go mod download
+        go install gotest.tools/gotestsum@latest
 
     - name: Test
-      run: go test -v ./...
+      run: |
+        gotestsum --format=standard-verbose --junitfile=junit.xml
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/junit.xml'
+        detailed_summary: true
+        include_passed: true
